### ISSUE TITLE
v1.0 安装后启动大部分组件-出现kernel异常提示 

### ISSUE THREAD

**Issue by wuy2022** [kelomina/KolominaAntiVirus#8]
系统win10 22h2 x64 安装mactype。通过蓝奏下载安装包后安装运行，只有弹窗拦截组件未报错。其余组件运行后弹窗kernel library未找到或异常。反复安装后仍未消除。
经检查火绒自定义规则未冲突。

另 其拦截了一个可疑进程后即崩溃。
\KolominaAntiVirus\log.log:
进程拦截:
2023/2/3
11:20:1
进程:backgroundTaskHost.exe
病毒路径:C:\Windows\System32\backgroundTaskHost.exe
病毒名:Heur/Enclosure.eXPressor
处理结果:进程结束失败

**Comment by kelomina** [comment]
能发下截图吗，我这边得看截图

**Comment by kelomina** [comment]
你好，由于您长期不回复，本帖将关闭
